baseURL = "https://metalblueberry.github.io/revelation/"
languageCode = "en-us"
title = "Revelation project template"

theme = ["reveal-hugo","code-snippets"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
